spring:
    datasource:
        url: jdbc:mysql://localhost:3306/stock_example
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 40
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql:
                            BasicBinder: trace
